def customer_type_features(ct):
    if ct=='New':
        cont_features=['COST_PER_CUST','COST_PER_CUST_LAG7','FLAG','NUM_EXEMPTIONS',	'NUM_DEPENDENTS',	'BUS_WILL_FILE_1099',	'BUS_REQUIRE_1099',	'AMOUNT_UNEMPLOYMENT',	'AMOUNT_TOTAL_TAX',	'AMOUNT_TOTAL_PAYMENTS',	'AMOUNT_TOTAL_DEDUCTIONS',	'AMOUNT_TAXES_PAID',	'AMOUNT_TAX_DUE',	'AMOUNT_TAX',	'AMOUNT_STUDENT_LOAN_INTEREST_DEDUCTION',	'AMOUNT_SCHE',	'AMOUNT_SALARIES_AND_WAGES',	'AMOUNT_REFUND',	'AMOUNT_REAL_ESTATE_TAX',	'AMOUNT_PERSONAL_PROPERTY_TAXES',	'AMOUNT_PAID_WITH_EXTENSION',	'AMOUNT_MOVING_EXPENSE',	'AMOUNT_MORTGAGE_POINTS_NON_1098',	'AMOUNT_MORTGAGE_INTEREST_NON_1098',	'AMOUNT_MORTGAGE_INTEREST',	'AMOUNT_MORTGAGE_INSURANCE',	'AMOUNT_INCOME_TAX_WITHHELD',	'AMOUNT_INCOME_TAX',	'AGI',	'AGE_TAXPAYER',	'AGE_SPOUSE',	'MINDBENDER_FLAG',	'CA_REFUND_TRANSFER_FLAG',	'REFUND_TRANSFER_FLAG',	'CA_AUDIT_DEFENSE_FLAG',	'AUDIT_DEFENSE_FLAG',	'CA_MAX_FLAG',	'MAX_FLAG',	'PS_FLAG',	'REQUIRED_TAKE_FLAG',	'FSCHC_FLAG',	'FSCHCEZ_FLAG',	'FSCHE_FLAG',	'FSCHA_FLAG',	'FSCHD_FLAG',	'FSCHF_FLAG',	'MISC1099_FLAG',	'RT_FLAG',	'student_taxpayer',	'_taxpayer',	'retired_taxpayer',	'unemployed_taxpayer',	'cashier_taxpayer',	'teacher_taxpayer',	'manager_taxpayer',	'sales_taxpayer',	'customerservice_taxpayer',	'laborer_taxpayer',	'cook_taxpayer',	'server_taxpayer',	'retail_taxpayer',	'engineer_taxpayer',	'military_taxpayer',	'cna_taxpayer',	'salesassociate_taxpayer',	'registerednurse_taxpayer',	'truckdriver_taxpayer',	'driver_taxpayer',	'mechanic_taxpayer',	'nurse_taxpayer',	'waitress_taxpayer',	'supervisor_taxpayer',	'labor_taxpayer',	'construction_taxpayer',	'warehouse_taxpayer',	'administrativeassistant_taxpayer',	'accountant_taxpayer',	'customerservicerep_taxpayer',	'clerk_taxpayer',	'receptionist_taxpayer',	'medicalassistant_taxpayer',	'disabled_taxpayer',	'softwareengineer_taxpayer',	'assistantmanager_taxpayer',	'officemanager_taxpayer',	'electrician_taxpayer',	'technician_taxpayer',	'none_taxpayer',	'machineoperator_taxpayer',	'caregiver_taxpayer',	'employed_taxpayer',	'bartender_taxpayer',	'projectmanager_taxpayer',	'maintenance_taxpayer',	'welder_taxpayer',	'housekeeper_taxpayer',	'homemaker_taxpayer',	'foodservice_taxpayer',	'selfemployed_taxpayer',	'chef_taxpayer',	'csr_taxpayer',	'warehouseworker_taxpayer',	'factoryworker_taxpayer',	'attorney_taxpayer',	'consultant_taxpayer',	'policeofficer_taxpayer',	'carpenter_taxpayer',	'secretary_taxpayer',	'rn_taxpayer',	'banker_taxpayer',	'operator_taxpayer',	'worker_taxpayer',	'security_taxpayer',	'production_taxpayer',	'socialworker_taxpayer',	'securityofficer_taxpayer',	'pharmacytechnician_taxpayer',	'machinist_taxpayer',	'barista_taxpayer',	'analyst_taxpayer',	'deliverydriver_taxpayer',	'stocker_taxpayer',	'factory_taxpayer',	'dentalassistant_taxpayer',	'custodian_taxpayer',	'generalmanager_taxpayer',	'employee_taxpayer',	'salesmanager_taxpayer',	'retailmanager_taxpayer',	'housekeeping_taxpayer',	'storemanager_taxpayer',	'securityguard_taxpayer',	'na_taxpayer',	'painter_taxpayer',	'accountmanager_taxpayer',	'correctionalofficer_taxpayer',	'lpn_taxpayer',	'operationsmanager_taxpayer',	'bankteller_taxpayer',	'fastfood_taxpayer',	'manufacturing_taxpayer',	'crewmember_taxpayer',	'generallabor_taxpayer',	'plumber_taxpayer',	'marketing_taxpayer',	'dispatcher_taxpayer',	'hostess_taxpayer',	'management_taxpayer',	'janitor_taxpayer',	'homemaker_spouse',	'retired_spouse',	'unemployed_spouse',	'teacher_spouse',	'student_spouse',	'housewife_spouse',	'none_spouse',	'disabled_spouse',	'home_maker_spouse',	'house_wife_spouse',	'stayathomemom_spouse',	'nurse_spouse',	'manager_spouse',	'registerednurse_spouse',	'sales_spouse',	'customerservice_spouse',	'cashier_spouse',	'na_spouse',	'laborer_spouse',	'retail_spouse',	'officemanager_spouse',	'administrativeassistant_spouse',	'engineer_spouse',	'secretary_spouse',	'accountant_spouse',	'cook_spouse',	'receptionist_spouse',	'truckdriver_spouse',	'self_employed_spouse',	'mechanic_spouse',	'rn_spouse',	'server_spouse',	'cna_spouse',	'driver_spouse',	'supervisor_spouse',	'medicalassistant_spouse',	'clerk_spouse',	'socialworker_spouse',	'projectmanager_spouse',	'salesassociate_spouse',	'mother_spouse',	'waitress_spouse',	'military_spouse',	'construction_spouse',	'attorney_spouse',	'electrician_spouse',	'dentalassistant_spouse',	'stayathomemother_spouse',	'customerservicerep_spouse',	'mom_spouse',	'substituteteacher_spouse',	'consultant_spouse',	'maintenance_spouse',	'policeofficer_spouse',	'banker_spouse',	'labor_spouse',	'welder_spouse',	'softwareengineer_spouse',	'na_spouse2',	'technician_spouse',	'marketing_spouse',	'assistantmanager_spouse',	'bankteller_spouse',	'stayathomeparent_spouse',	'caregiver_spouse',	'warehouse_spouse',	'educator_spouse',	'carpenter_spouse',	'bookkeeper_spouse',	'housekeeper_spouse',	'physician_spouse',	'clerical_spouse',	'analyst_spouse',	'paralegal_spouse',	'pharmacist_spouse',	'machineoperator_spouse',	'chef_spouse',	'physicaltherapist_spouse',	'humanresources_spouse',	'lpn_spouse',	'foodservice_spouse',	'pharmacytechnician_spouse',	'executiveassistant_spouse',	'officeassistant_spouse',	'disable_spouse',	'salesmanager_spouse',	'accountmanager_spouse',	'professor_spouse',	'hairstylist_spouse',	'machinist_spouse',	'selfemployed_spouse',	'custodian_spouse',	'factoryworker_spouse',	'retailmanager_spouse',	'director_spouse',	'graphicdesigner_spouse',	'bartender_spouse',	'administrator_spouse',	'home_spouse',	'accounting_spouse',	'unemployeed_spouse',	'SESSIONS_TO_COMPLETE',	'FLAG_ITEMIZE_SEPARATELY',	'TOTAL_REVENUE']

        bool_features=['FLAG','MINDBENDER_FLAG',	'CA_REFUND_TRANSFER_FLAG',	'REFUND_TRANSFER_FLAG',	'CA_AUDIT_DEFENSE_FLAG',	'AUDIT_DEFENSE_FLAG',	'CA_MAX_FLAG',	'MAX_FLAG',	'PS_FLAG',	'REQUIRED_TAKE_FLAG',	'FSCHC_FLAG',	'FSCHCEZ_FLAG',	'FSCHE_FLAG',	'FSCHA_FLAG',	'FSCHD_FLAG',	'FSCHF_FLAG',	'MISC1099_FLAG',	'RT_FLAG',	'student_taxpayer',	'_taxpayer',	'retired_taxpayer',	'unemployed_taxpayer',	'cashier_taxpayer',	'teacher_taxpayer',	'manager_taxpayer',	'sales_taxpayer',	'customerservice_taxpayer',	'laborer_taxpayer',	'cook_taxpayer',	'server_taxpayer',	'retail_taxpayer',	'engineer_taxpayer',	'military_taxpayer',	'cna_taxpayer',	'salesassociate_taxpayer',	'registerednurse_taxpayer',	'truckdriver_taxpayer',	'driver_taxpayer',	'mechanic_taxpayer',	'nurse_taxpayer',	'waitress_taxpayer',	'supervisor_taxpayer',	'labor_taxpayer',	'construction_taxpayer',	'warehouse_taxpayer',	'administrativeassistant_taxpayer',	'accountant_taxpayer',	'customerservicerep_taxpayer',	'clerk_taxpayer',	'receptionist_taxpayer',	'medicalassistant_taxpayer',	'disabled_taxpayer',	'softwareengineer_taxpayer',	'assistantmanager_taxpayer',	'officemanager_taxpayer',	'electrician_taxpayer',	'technician_taxpayer',	'none_taxpayer',	'machineoperator_taxpayer',	'caregiver_taxpayer',	'employed_taxpayer',	'bartender_taxpayer',	'projectmanager_taxpayer',	'maintenance_taxpayer',	'welder_taxpayer',	'housekeeper_taxpayer',	'homemaker_taxpayer',	'foodservice_taxpayer',	'selfemployed_taxpayer',	'chef_taxpayer',	'csr_taxpayer',	'warehouseworker_taxpayer',	'factoryworker_taxpayer',	'attorney_taxpayer',	'consultant_taxpayer',	'policeofficer_taxpayer',	'carpenter_taxpayer',	'secretary_taxpayer',	'rn_taxpayer',	'banker_taxpayer',	'operator_taxpayer',	'worker_taxpayer',	'security_taxpayer',	'production_taxpayer',	'socialworker_taxpayer',	'securityofficer_taxpayer',	'pharmacytechnician_taxpayer',	'machinist_taxpayer',	'barista_taxpayer',	'analyst_taxpayer',	'deliverydriver_taxpayer',	'stocker_taxpayer',	'factory_taxpayer',	'dentalassistant_taxpayer',	'custodian_taxpayer',	'generalmanager_taxpayer',	'employee_taxpayer',	'salesmanager_taxpayer',	'retailmanager_taxpayer',	'housekeeping_taxpayer',	'storemanager_taxpayer',	'securityguard_taxpayer',	'na_taxpayer',	'painter_taxpayer',	'accountmanager_taxpayer',	'correctionalofficer_taxpayer',	'lpn_taxpayer',	'operationsmanager_taxpayer',	'bankteller_taxpayer',	'fastfood_taxpayer',	'manufacturing_taxpayer',	'crewmember_taxpayer',	'generallabor_taxpayer',	'plumber_taxpayer',	'marketing_taxpayer',	'dispatcher_taxpayer',	'hostess_taxpayer',	'management_taxpayer',	'janitor_taxpayer',	'homemaker_spouse',	'retired_spouse',	'unemployed_spouse',	'teacher_spouse',	'student_spouse',	'housewife_spouse',	'none_spouse',	'disabled_spouse',	'home_maker_spouse',	'house_wife_spouse',	'stayathomemom_spouse',	'nurse_spouse',	'manager_spouse',	'registerednurse_spouse',	'sales_spouse',	'customerservice_spouse',	'cashier_spouse',	'na_spouse',	'laborer_spouse',	'retail_spouse',	'officemanager_spouse',	'administrativeassistant_spouse',	'engineer_spouse',	'secretary_spouse',	'accountant_spouse',	'cook_spouse',	'receptionist_spouse',	'truckdriver_spouse',	'self_employed_spouse',	'mechanic_spouse',	'rn_spouse',	'server_spouse',	'cna_spouse',	'driver_spouse',	'supervisor_spouse',	'medicalassistant_spouse',	'clerk_spouse',	'socialworker_spouse',	'projectmanager_spouse',	'salesassociate_spouse',	'mother_spouse',	'waitress_spouse',	'military_spouse',	'construction_spouse',	'attorney_spouse',	'electrician_spouse',	'dentalassistant_spouse',	'stayathomemother_spouse',	'customerservicerep_spouse',	'mom_spouse',	'substituteteacher_spouse',	'consultant_spouse',	'maintenance_spouse',	'policeofficer_spouse',	'banker_spouse',	'labor_spouse',	'welder_spouse',	'softwareengineer_spouse',	'na_spouse2',	'technician_spouse',	'marketing_spouse',	'assistantmanager_spouse',	'bankteller_spouse',	'stayathomeparent_spouse',	'caregiver_spouse',	'warehouse_spouse',	'educator_spouse',	'carpenter_spouse',	'bookkeeper_spouse',	'housekeeper_spouse',	'physician_spouse',	'clerical_spouse',	'analyst_spouse',	'paralegal_spouse',	'pharmacist_spouse',	'machineoperator_spouse',	'chef_spouse',	'physicaltherapist_spouse',	'humanresources_spouse',	'lpn_spouse',	'foodservice_spouse',	'pharmacytechnician_spouse',	'executiveassistant_spouse',	'officeassistant_spouse',	'disable_spouse',	'salesmanager_spouse',	'accountmanager_spouse',	'professor_spouse',	'hairstylist_spouse',	'machinist_spouse',	'selfemployed_spouse',	'custodian_spouse',	'factoryworker_spouse',	'retailmanager_spouse',	'director_spouse',	'graphicdesigner_spouse',	'bartender_spouse',	'administrator_spouse',	'home_spouse',	'accounting_spouse',	'unemployeed_spouse']
        catag_features=['TAX_WEEK','STATE_ATTACH_COUNT',	'PRS_SCORE',	'REJECT_COUNT',	'NUM_W2',	'NUM_SCHE',	'NUM_SCHC',	'FLAG_ITEMIZED_DEDUCTIONS',	'START_SKU',	'IMPORT_TYPE',	'FIRST_COMPLETE_APP_TYPE',	'FIRST_COMPLETE_DEVICE_TYPE',	'START_DEVICE_TYPE',	'VAUTH_DEVICE_TYPE',	'NEAUTH_DEVICE_TYPE',	'START_SKU_ROLLUP',	'FED_FORM_TYPE',	'PRODUCT_EDITION_DESCRIPTION',	'CUSTOMER_TYPE',	'COMPLETED_SKU',	'LAST_STATUS',	'FILING_STATUS',	'DMA_AREA']

        cont_score_features = ['COST_PER_CUST','COST_PER_CUST_LAG7', 'NUM_EXEMPTIONS', 'NUM_DEPENDENTS', 'BUS_WILL_FILE_1099', 'BUS_REQUIRE_1099',
                         'AMOUNT_UNEMPLOYMENT', 'AMOUNT_TOTAL_TAX', 'AMOUNT_TOTAL_PAYMENTS', 'AMOUNT_TOTAL_DEDUCTIONS',
                         'AMOUNT_TAXES_PAID', 'AMOUNT_TAX_DUE', 'AMOUNT_TAX', 'AMOUNT_STUDENT_LOAN_INTEREST_DEDUCTION',
                         'AMOUNT_SCHE', 'AMOUNT_SALARIES_AND_WAGES', 'AMOUNT_REFUND', 'AMOUNT_REAL_ESTATE_TAX',
                         'AMOUNT_PERSONAL_PROPERTY_TAXES', 'AMOUNT_PAID_WITH_EXTENSION', 'AMOUNT_MOVING_EXPENSE',
                         'AMOUNT_MORTGAGE_POINTS_NON_1098', 'AMOUNT_MORTGAGE_INTEREST_NON_1098',
                         'AMOUNT_MORTGAGE_INTEREST', 'AMOUNT_MORTGAGE_INSURANCE', 'AMOUNT_INCOME_TAX_WITHHELD',
                         'AMOUNT_INCOME_TAX', 'AGI', 'AGE_TAXPAYER', 'AGE_SPOUSE', 'MINDBENDER_FLAG',
                         'CA_REFUND_TRANSFER_FLAG', 'REFUND_TRANSFER_FLAG', 'CA_AUDIT_DEFENSE_FLAG',
                         'AUDIT_DEFENSE_FLAG', 'CA_MAX_FLAG', 'MAX_FLAG', 'PS_FLAG', 'REQUIRED_TAKE_FLAG', 'FSCHC_FLAG',
                         'FSCHCEZ_FLAG', 'FSCHE_FLAG', 'FSCHA_FLAG', 'FSCHD_FLAG', 'FSCHF_FLAG', 'MISC1099_FLAG',
                          'RT_FLAG', 'student_taxpayer', '_taxpayer', 'retired_taxpayer',
                         'unemployed_taxpayer', 'cashier_taxpayer', 'teacher_taxpayer', 'manager_taxpayer',
                         'sales_taxpayer', 'customerservice_taxpayer', 'laborer_taxpayer', 'cook_taxpayer',
                         'server_taxpayer', 'retail_taxpayer', 'engineer_taxpayer', 'military_taxpayer', 'cna_taxpayer',
                         'salesassociate_taxpayer', 'registerednurse_taxpayer', 'truckdriver_taxpayer',
                         'driver_taxpayer', 'mechanic_taxpayer', 'nurse_taxpayer', 'waitress_taxpayer',
                         'supervisor_taxpayer', 'labor_taxpayer', 'construction_taxpayer', 'warehouse_taxpayer',
                         'administrativeassistant_taxpayer', 'accountant_taxpayer', 'customerservicerep_taxpayer',
                         'clerk_taxpayer', 'receptionist_taxpayer', 'medicalassistant_taxpayer', 'disabled_taxpayer',
                         'softwareengineer_taxpayer', 'assistantmanager_taxpayer', 'officemanager_taxpayer',
                         'electrician_taxpayer', 'technician_taxpayer', 'none_taxpayer', 'machineoperator_taxpayer',
                         'caregiver_taxpayer', 'employed_taxpayer', 'bartender_taxpayer', 'projectmanager_taxpayer',
                         'maintenance_taxpayer', 'welder_taxpayer', 'housekeeper_taxpayer', 'homemaker_taxpayer',
                         'foodservice_taxpayer', 'selfemployed_taxpayer', 'chef_taxpayer', 'csr_taxpayer',
                         'warehouseworker_taxpayer', 'factoryworker_taxpayer', 'attorney_taxpayer',
                         'consultant_taxpayer', 'policeofficer_taxpayer', 'carpenter_taxpayer', 'secretary_taxpayer',
                         'rn_taxpayer', 'banker_taxpayer', 'operator_taxpayer', 'worker_taxpayer', 'security_taxpayer',
                         'production_taxpayer', 'socialworker_taxpayer', 'securityofficer_taxpayer',
                         'pharmacytechnician_taxpayer', 'machinist_taxpayer', 'barista_taxpayer', 'analyst_taxpayer',
                         'deliverydriver_taxpayer', 'stocker_taxpayer', 'factory_taxpayer', 'dentalassistant_taxpayer',
                         'custodian_taxpayer', 'generalmanager_taxpayer', 'employee_taxpayer', 'salesmanager_taxpayer',
                         'retailmanager_taxpayer', 'housekeeping_taxpayer', 'storemanager_taxpayer',
                         'securityguard_taxpayer', 'na_taxpayer', 'painter_taxpayer', 'accountmanager_taxpayer',
                         'correctionalofficer_taxpayer', 'lpn_taxpayer', 'operationsmanager_taxpayer',
                         'bankteller_taxpayer', 'fastfood_taxpayer', 'manufacturing_taxpayer', 'crewmember_taxpayer',
                         'generallabor_taxpayer', 'plumber_taxpayer', 'marketing_taxpayer', 'dispatcher_taxpayer',
                         'hostess_taxpayer', 'management_taxpayer', 'janitor_taxpayer', 'homemaker_spouse',
                         'retired_spouse', 'unemployed_spouse', 'teacher_spouse', 'student_spouse', 'housewife_spouse',
                         'none_spouse', 'disabled_spouse', 'home_maker_spouse', 'house_wife_spouse',
                         'stayathomemom_spouse', 'nurse_spouse', 'manager_spouse', 'registerednurse_spouse',
                         'sales_spouse', 'customerservice_spouse', 'cashier_spouse', 'na_spouse', 'laborer_spouse',
                         'retail_spouse', 'officemanager_spouse', 'administrativeassistant_spouse', 'engineer_spouse',
                         'secretary_spouse', 'accountant_spouse', 'cook_spouse', 'receptionist_spouse',
                         'truckdriver_spouse', 'self_employed_spouse', 'mechanic_spouse', 'rn_spouse', 'server_spouse',
                         'cna_spouse', 'driver_spouse', 'supervisor_spouse', 'medicalassistant_spouse', 'clerk_spouse',
                         'socialworker_spouse', 'projectmanager_spouse', 'salesassociate_spouse', 'mother_spouse',
                         'waitress_spouse', 'military_spouse', 'construction_spouse', 'attorney_spouse',
                         'electrician_spouse', 'dentalassistant_spouse', 'stayathomemother_spouse',
                         'customerservicerep_spouse', 'mom_spouse', 'substituteteacher_spouse', 'consultant_spouse',
                         'maintenance_spouse', 'policeofficer_spouse', 'banker_spouse', 'labor_spouse', 'welder_spouse',
                         'softwareengineer_spouse', 'na_spouse2', 'technician_spouse', 'marketing_spouse',
                         'assistantmanager_spouse', 'bankteller_spouse', 'stayathomeparent_spouse', 'caregiver_spouse',
                         'warehouse_spouse', 'educator_spouse', 'carpenter_spouse', 'bookkeeper_spouse',
                         'housekeeper_spouse', 'physician_spouse', 'clerical_spouse', 'analyst_spouse',
                         'paralegal_spouse', 'pharmacist_spouse', 'machineoperator_spouse', 'chef_spouse',
                         'physicaltherapist_spouse', 'humanresources_spouse', 'lpn_spouse', 'foodservice_spouse',
                         'pharmacytechnician_spouse', 'executiveassistant_spouse', 'officeassistant_spouse',
                         'disable_spouse', 'salesmanager_spouse', 'accountmanager_spouse', 'professor_spouse',
                         'hairstylist_spouse', 'machinist_spouse', 'selfemployed_spouse', 'custodian_spouse',
                         'factoryworker_spouse', 'retailmanager_spouse', 'director_spouse', 'graphicdesigner_spouse',
                         'bartender_spouse', 'administrator_spouse', 'home_spouse', 'accounting_spouse',
                         'unemployeed_spouse', 'SESSIONS_TO_COMPLETE', 'FLAG_ITEMIZE_SEPARATELY', 'TOTAL_REVENUE']

        bool_score_features = [ 'MINDBENDER_FLAG', 'CA_REFUND_TRANSFER_FLAG', 'REFUND_TRANSFER_FLAG',
                         'CA_AUDIT_DEFENSE_FLAG', 'AUDIT_DEFENSE_FLAG', 'CA_MAX_FLAG', 'MAX_FLAG', 'PS_FLAG',
                         'REQUIRED_TAKE_FLAG', 'FSCHC_FLAG', 'FSCHCEZ_FLAG', 'FSCHE_FLAG', 'FSCHA_FLAG', 'FSCHD_FLAG',
                         'FSCHF_FLAG', 'MISC1099_FLAG',  'RT_FLAG', 'student_taxpayer', '_taxpayer',
                         'retired_taxpayer', 'unemployed_taxpayer', 'cashier_taxpayer', 'teacher_taxpayer',
                         'manager_taxpayer', 'sales_taxpayer', 'customerservice_taxpayer', 'laborer_taxpayer',
                         'cook_taxpayer', 'server_taxpayer', 'retail_taxpayer', 'engineer_taxpayer',
                         'military_taxpayer', 'cna_taxpayer', 'salesassociate_taxpayer', 'registerednurse_taxpayer',
                         'truckdriver_taxpayer', 'driver_taxpayer', 'mechanic_taxpayer', 'nurse_taxpayer',
                         'waitress_taxpayer', 'supervisor_taxpayer', 'labor_taxpayer', 'construction_taxpayer',
                         'warehouse_taxpayer', 'administrativeassistant_taxpayer', 'accountant_taxpayer',
                         'customerservicerep_taxpayer', 'clerk_taxpayer', 'receptionist_taxpayer',
                         'medicalassistant_taxpayer', 'disabled_taxpayer', 'softwareengineer_taxpayer',
                         'assistantmanager_taxpayer', 'officemanager_taxpayer', 'electrician_taxpayer',
                         'technician_taxpayer', 'none_taxpayer', 'machineoperator_taxpayer', 'caregiver_taxpayer',
                         'employed_taxpayer', 'bartender_taxpayer', 'projectmanager_taxpayer', 'maintenance_taxpayer',
                         'welder_taxpayer', 'housekeeper_taxpayer', 'homemaker_taxpayer', 'foodservice_taxpayer',
                         'selfemployed_taxpayer', 'chef_taxpayer', 'csr_taxpayer', 'warehouseworker_taxpayer',
                         'factoryworker_taxpayer', 'attorney_taxpayer', 'consultant_taxpayer', 'policeofficer_taxpayer',
                         'carpenter_taxpayer', 'secretary_taxpayer', 'rn_taxpayer', 'banker_taxpayer',
                         'operator_taxpayer', 'worker_taxpayer', 'security_taxpayer', 'production_taxpayer',
                         'socialworker_taxpayer', 'securityofficer_taxpayer', 'pharmacytechnician_taxpayer',
                         'machinist_taxpayer', 'barista_taxpayer', 'analyst_taxpayer', 'deliverydriver_taxpayer',
                         'stocker_taxpayer', 'factory_taxpayer', 'dentalassistant_taxpayer', 'custodian_taxpayer',
                         'generalmanager_taxpayer', 'employee_taxpayer', 'salesmanager_taxpayer',
                         'retailmanager_taxpayer', 'housekeeping_taxpayer', 'storemanager_taxpayer',
                         'securityguard_taxpayer', 'na_taxpayer', 'painter_taxpayer', 'accountmanager_taxpayer',
                         'correctionalofficer_taxpayer', 'lpn_taxpayer', 'operationsmanager_taxpayer',
                         'bankteller_taxpayer', 'fastfood_taxpayer', 'manufacturing_taxpayer', 'crewmember_taxpayer',
                         'generallabor_taxpayer', 'plumber_taxpayer', 'marketing_taxpayer', 'dispatcher_taxpayer',
                         'hostess_taxpayer', 'management_taxpayer', 'janitor_taxpayer', 'homemaker_spouse',
                         'retired_spouse', 'unemployed_spouse', 'teacher_spouse', 'student_spouse', 'housewife_spouse',
                         'none_spouse', 'disabled_spouse', 'home_maker_spouse', 'house_wife_spouse',
                         'stayathomemom_spouse', 'nurse_spouse', 'manager_spouse', 'registerednurse_spouse',
                         'sales_spouse', 'customerservice_spouse', 'cashier_spouse', 'na_spouse', 'laborer_spouse',
                         'retail_spouse', 'officemanager_spouse', 'administrativeassistant_spouse', 'engineer_spouse',
                         'secretary_spouse', 'accountant_spouse', 'cook_spouse', 'receptionist_spouse',
                         'truckdriver_spouse', 'self_employed_spouse', 'mechanic_spouse', 'rn_spouse', 'server_spouse',
                         'cna_spouse', 'driver_spouse', 'supervisor_spouse', 'medicalassistant_spouse', 'clerk_spouse',
                         'socialworker_spouse', 'projectmanager_spouse', 'salesassociate_spouse', 'mother_spouse',
                         'waitress_spouse', 'military_spouse', 'construction_spouse', 'attorney_spouse',
                         'electrician_spouse', 'dentalassistant_spouse', 'stayathomemother_spouse',
                         'customerservicerep_spouse', 'mom_spouse', 'substituteteacher_spouse', 'consultant_spouse',
                         'maintenance_spouse', 'policeofficer_spouse', 'banker_spouse', 'labor_spouse', 'welder_spouse',
                         'softwareengineer_spouse', 'na_spouse2', 'technician_spouse', 'marketing_spouse',
                         'assistantmanager_spouse', 'bankteller_spouse', 'stayathomeparent_spouse', 'caregiver_spouse',
                         'warehouse_spouse', 'educator_spouse', 'carpenter_spouse', 'bookkeeper_spouse',
                         'housekeeper_spouse', 'physician_spouse', 'clerical_spouse', 'analyst_spouse',
                         'paralegal_spouse', 'pharmacist_spouse', 'machineoperator_spouse', 'chef_spouse',
                         'physicaltherapist_spouse', 'humanresources_spouse', 'lpn_spouse', 'foodservice_spouse',
                         'pharmacytechnician_spouse', 'executiveassistant_spouse', 'officeassistant_spouse',
                         'disable_spouse', 'salesmanager_spouse', 'accountmanager_spouse', 'professor_spouse',
                         'hairstylist_spouse', 'machinist_spouse', 'selfemployed_spouse', 'custodian_spouse',
                         'factoryworker_spouse', 'retailmanager_spouse', 'director_spouse', 'graphicdesigner_spouse',
                         'bartender_spouse', 'administrator_spouse', 'home_spouse', 'accounting_spouse',
                         'unemployeed_spouse']
        catag_score_features = ['TAX_WEEK','STATE_ATTACH_COUNT', 'PRS_SCORE', 'REJECT_COUNT', 'NUM_W2', 'NUM_SCHE', 'NUM_SCHC',
                          'FLAG_ITEMIZED_DEDUCTIONS', 'START_SKU',   'IMPORT_TYPE',
                          'FIRST_COMPLETE_APP_TYPE', 'FIRST_COMPLETE_DEVICE_TYPE', 'START_DEVICE_TYPE',
                          'VAUTH_DEVICE_TYPE', 'NEAUTH_DEVICE_TYPE', 'START_SKU_ROLLUP', 'FED_FORM_TYPE',
                          'PRODUCT_EDITION_DESCRIPTION', 'CUSTOMER_TYPE', 'COMPLETED_SKU', 'LAST_STATUS',
                          'FILING_STATUS', 'DMA_AREA']



    return cont_features, bool_features, catag_features, cont_score_features, bool_score_features, catag_score_features